<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.5.2 setup script
 * Date: Wed, 21 Dec 2016 12:27:48 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Gift Jeenie [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Gift Jeenie';
$cfg['Servers'][$i]['host'] = '40.71.41.225';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'giftjeenie';
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'd}f%]8-[Y8r6#Qsg82Hsdzn1+S<k%9D_';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
